version: "3.9"
networks:
  myAppNetwork:
    driver: bridge

services:
  postgresServerDb:
    container_name: container-postgres
    image: postgres:latest
    ports:
      - "5022:5432"
    environment:
      - POSTGRES_USER=pv212api
      - POSTGRES_PASSWORD=*dmUntdOidd3d_#WTi4B9ZoZp%rSDj4Imds07djc*
      - POSTGRES_DB=pv212Db
    networks:
      - myAppNetwork
    volumes:
#       - d:/web/pv212/postgresql:/var/lib/postgresql/data  # Use the volume name msvol here
        - /data/postgresql/data:/var/lib/postgresql/data
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5

  app:
    container_name: pv212_container
    image: novakvova/java-pv212-api
    ports:
      - "4082:8084"
    networks:
     - myAppNetwork
    depends_on:
      - postgresServerDb
    volumes:
#     - d:/volumes/pv212-java/images:/app/images  # Use the volume name appvol here
     - /volumes/pv212-java/images:/app/images  # Use the volume name appvol here
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 5
  
  client:
    container_name: pv212_client_container
    image: novakvova/pv212_client
    restart: on-failure
    ports:
      - "4081:80"
      

